version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    environment:
      - PORT=3000
    command: sh -c "npx prisma generate && yarn start:dev"